# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Linux: Blender 3.1"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2

    - name: Install Blender
      run: |
        sudo apt-get update -qq
        # sudo apt-get install blender

    - name: Install Pip
      run: |
        python -m pip install --upgrade pip

    - name: Download Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Prepare env
      run: |
        source $HOME/.poetry/env
        poetry install --no-root
        poetry run python utils/download_blender.py

    # - name: Download Blender
    #   run: |


    - name: Test with pytest
      run: |
        python tests.py ../blender-linux/blender

